use anyhow::{Context, Result};

use crate::aa_masses::AminoMasses;
use crate::variant::Variant;

pub fn build_dummy_entry<W: std::io::Write>(
    enst: &str,
    var: Vec<Variant>,
    mut seq: String,
    masses_dict: &AminoMasses,
    mut writer: W,
) -> Result<()> {
    let mut ft_lines = String::new();

    seq.truncate(seq.find('*').unwrap_or(seq.len()));

    let last_aa = seq.trim_end().chars().last();

    let seqs = format_seq(&seq, masses_dict).context(format!("Failed for {}", enst))?;

    if let Some(last_aa_valid) = last_aa {
        for mut variant in var {
            variant.normalize(seq.len() as u32, last_aa_valid);
            ft_lines.push_str(&variant.to_uniprot(seq.len() as u32)?);
        }
    }

    let entry = format!(
        "ID   {}              Unreviewed;          {} AA.\n\
        AC   {};\n\
        DT   1-JAN-1970, integrated into DUMMY.\n\
        DT   1-JAN-1970, sequence version 1.\n\
        DT   1-JAN-1970, entry version 1.\n\
        DE   RecName: Full={}.\n\
        GN   Name={}; Synonyms={}; ORFNames={};\n\
        OS   dummy organism (DUMMY).\n\
        OC   Unclassified; dummy (DUMMY).\n\
        OX   NCBI_TaxID=0000;\n\
        RN   [1]\n\
        RP   AUTOGENERATED.\n\
        RA   Autogenerated;\n\
        RT   \"This is an autogenerated entry.\";\n\
        RL   Unpublished.\n\
        CC   -!- CAUTION: This entry was autogenerated and sequences\n\
        CC       can differ from UniProt!\n\
        DR   UTA; {}; Universal Transcript Archive.\n\
        PE   4: Predicted;\n\
        KW   Generated for ProtGraph.\n\
    {}\
    {}\
        //\n",
        enst,
        seq.len(),
        enst,
        enst,
        enst, enst, enst,   // GN
        enst,               // DR
        ft_lines,
        seqs
    );

    writer.write_all(entry.as_bytes())?;
    Ok(())
}

pub fn format_seq(seq: &str, masses_dict: &AminoMasses) -> Result<String> {
    let mass = masses_dict.sequence_mass(seq)?.round() as u64;

    Ok(format!(
        "SQ   SEQUENCE {} AA; {} MW; {} CRC64;\n{}",
        seq.len(),
        mass,
        "0000000000000000",
        format_sequence(seq)?
    ))
}

fn format_sequence(seq: &str) -> Result<String> {
    let mut result = String::new();
    let chars: Vec<char> = seq.chars().collect();

    for chunk in chars.chunks(60) {
        result.push_str("     ");

        for (j, group) in chunk.chunks(10).enumerate() {
            if j > 0 {
                result.push(' ');
            }
            result.push_str(&group.iter().collect::<String>());
        }
        result.push('\n');
    }

    Ok(result)
}
